# Generated by Django 3.2.3 on 2021-06-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('surname', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=122)),
                ('add', models.CharField(max_length=122)),
                ('file', models.FileField(upload_to='')),
                ('pwd', models.CharField(max_length=122)),
                ('rpwd', models.CharField(max_length=122)),
            ],
        ),
    ]
