# Generated by Django 3.2.3 on 2021-06-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210617_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='file',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
