# Generated by Django 3.2.3 on 2021-06-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_signup_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtName', models.CharField(max_length=122)),
                ('BullyingType', models.BooleanField(default=False)),
                ('ResultInInjury', models.BooleanField(default=False)),
                ('BullyBehaviors', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=122)),
                ('Description', models.CharField(max_length=122)),
                ('PhysicalEvidence', models.BooleanField(default=False)),
                ('fileUpload', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
