# Generated by Django 3.2.3 on 2021-06-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='BullyBehaviors',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='BullyingType',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ResultInInjury',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='PhysicalEvidence',
            field=models.CharField(max_length=122),
        ),
    ]
