# Generated by Django 3.2.3 on 2021-06-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210619_0511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='txtName',
            new_name='name',
        ),
    ]
